export const GET_DOGS = 'GET_DOGS';
export const GET_DOG_BY_NAME = 'GET_DOG_BY_NAME';
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';
export const NAME_BY_ORIGIN = 'NAME_BY_ORIGIN';
export const TEMP_ALL_NAMES = 'TEMP_ALL_NAMES';
export const ALPHABETIC_ORDER = 'ALPHABETIC_ORDER';
export const ORDER_BY_WEIGHT = 'ORDER_BY_WEIGHT';
export const POST_DOG = 'POST_DOG';